-- Ministry of Education — diplomas, equivalences, scholarships

CREATE TABLE IF NOT EXISTS education_records (
    cin                VARCHAR(20) PRIMARY KEY,
    diplomas           JSONB DEFAULT '[]'::jsonb,
    equivalences       JSONB DEFAULT '[]'::jsonb,
    scholarships       JSONB DEFAULT '[]'::jsonb,
    current_enrollment VARCHAR(255),
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO education_records (cin, diplomas, equivalences, scholarships, current_enrollment) VALUES
('10000001',
 '[{"level":"BSc","title":"Mechanical Engineering","institution":"National Polytechnic","year":2011,"grade":"Honors","verified":true},
   {"level":"MSc","title":"Industrial Engineering","institution":"National Polytechnic","year":2013,"grade":"Distinction","verified":true}]',
 '[]', '[]', NULL),
('10000002',
 '[{"level":"MD","title":"Doctor of Medicine","institution":"Medical University","year":2020,"grade":"Magna Cum Laude","verified":true},
   {"level":"BSc","title":"Biology","institution":"Medical University","year":2017,"grade":"First Class","verified":true}]',
 '[]',
 '[{"name":"Merit Scholarship","amount":5000,"currency":"USD","year":2016,"institution":"Medical University"}]',
 'Residency - Cardiology (Year 2)'),
('10000003',
 '[{"level":"MBA","title":"Business Administration","institution":"National Business School","year":2005,"grade":"Pass","verified":true},
   {"level":"BSc","title":"Economics","institution":"State University","year":2001,"grade":"Second Class","verified":true}]',
 '[]', '[]', NULL),
('10000004',
 '[{"level":"MEd","title":"Education Sciences","institution":"Teachers College","year":2016,"grade":"Distinction","verified":true},
   {"level":"BA","title":"English Literature","institution":"State University","year":2014,"grade":"First Class","verified":true}]',
 '[]',
 '[{"name":"Teaching Excellence Grant","amount":2000,"currency":"USD","year":2015,"institution":"Ministry of Education"}]',
 NULL),
('10000005',
 '[{"level":"BSc","title":"Military Sciences","institution":"National Military Academy","year":1991,"grade":"With Honors","verified":true}]',
 '[]', '[]', NULL),
('10000006',
 '[{"level":"Baccalaureate","title":"Science Track","institution":"East Borough High School","year":2018,"grade":"Very Good","verified":true}]',
 '[]',
 '[{"name":"National Merit Scholarship","amount":8000,"currency":"USD","year":2018,"institution":"Ministry of Education"},
   {"name":"STEM Excellence Award","amount":3000,"currency":"USD","year":2020,"institution":"Tech Foundation"}]',
 'BSc Computer Science - Year 4, National University'),
('10000007',
 '[{"level":"LLM","title":"International Law","institution":"National Law School","year":2010,"grade":"Distinction","verified":true},
   {"level":"LLB","title":"Law","institution":"National Law School","year":2007,"grade":"First Class","verified":true}]',
 '[{"foreign_diploma":"LLM Harvard Law","local_equivalent":"LLM International Law","year":2012,"verified":true}]',
 '[]', NULL),
('10000008',
 '[{"level":"BSN","title":"Nursing Science","institution":"Health Sciences Institute","year":2009,"grade":"Honors","verified":true},
   {"level":"MSN","title":"Pediatric Nursing","institution":"Health Sciences Institute","year":2014,"grade":"Pass","verified":true}]',
 '[]', '[]', NULL),
('10000009',
 '[{"level":"BAgr","title":"Agricultural Sciences","institution":"Agricultural College","year":1996,"grade":"Pass","verified":true}]',
 '[]', '[]', NULL),
('10000010',
 '[{"level":"MSc","title":"Computer Science","institution":"Northern Technical University","year":2019,"grade":"Summa Cum Laude","verified":true},
   {"level":"BSc","title":"Software Engineering","institution":"Northern Technical University","year":2017,"grade":"First Class","verified":true}]',
 '[{"foreign_diploma":"BSc Software Eng (Sweden)","local_equivalent":"BSc Computer Science","year":2018,"verified":true}]',
 '[{"name":"International Student Grant","amount":10000,"currency":"USD","year":2017,"institution":"Northern Tech"}]',
 NULL)
ON CONFLICT (cin) DO NOTHING;
